source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.2.2"

gem "rails", "~> 7.0.5"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "bcrypt", "~> 3.1.7"
gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]
gem "bootsnap", require: false

group :development, :test do
  gem "byebug"
  gem "standard"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker", "~> 3.2"
end

gem "graphql", "~> 2.0"
gem "apollo-federation", "~> 3.8"

gem "graphql-rails-generators", "~> 1.1"

gem "apollo_upload_server"

gem 'aws-sdk-s3'
gem "rails_event_store", "~> 2.9"
gem "search_object_graphql"
gem "graphql-fragment_cache"
gem "graphql-batch", "~> 0.5.3"

group :test do
  gem "ruby_event_store-rspec"
end
gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => :development
gem "ruby-lsp-rails", :group => :development
